### ISSUE TITLE
Data cannot be added to a report

### ISSUE THREAD

**Issue by 04cfb1ed** [nossralf/code-insights-rs#2]
Hello

I am using your library to create the structure of a report with this code:

```rust
let result = ReportResult::Pass;
let reporter = "The reporter";

ReportBuilder::new("Title")
    .details("Details")
    .result(result)
    .reporter(reporter)
    .data(vec![
        Data {
            title: "Results",
            parameter: Parameter::Boolean(true)
        }
    ])
    .build()
    .unwrap();
``` 

There is AnnotationBuilder, ReportBuilder but not DataBuilder therefore I cannot create Data struct (private fields)

**Workaround:** I am using serde json to do the inverse process

```rust
let result = ReportResult::Pass;
let reporter = "The reporter";

let p: Data = serde_json::from_str(
    r#"{"title": "Results", "parameter": {"type": "PERCENTAGE", "value": 75}}"#,
)
.unwrap();

ReportBuilder::new("Title")
    .details("Details")
    .result(result)
    .reporter(reporter)
    .data(vec![p])
    .build()
    .unwrap();
```

**Comment by nossralf** [comment]
Thanks for the report. I made the fields of `Data` public since Bitbucket doesn't impose any length limitations and a builder for a struct with two fields feels less ergonomic.

Released 0.1.1 with this fix.
